### ISSUE TITLE
Please release version 0.4.18.1 to Hackage

### ISSUE THREAD

**Issue by danwdart** [nurpax/sqlite-simple#95] opened 2021-06-29 19:36 UTC
It would be really nice to be able to auto-derive these instances just like I can for `ToJSON`/`FromJSON` in `aeson`.

**Comment by danwdart** [comment] 2021-06-30 08:06
Durr, it seems that this exists in the repository on "version" 0.4.18.1, but that this is not tagged, and only 0.4.16.0 is tagged on GitHub and only 0.4.18.0 is released to Hackage, not 0.4.18.1. So it's not quite the same as #84, it's a new issue that 0.4.18.1 isn't in Hackage whilst 0.4.18.0 is.

**Comment by danwdart** [comment] 2021-06-30 08:06
Changed title accordingly.

**Comment by sigrlami** [comment] 2021-08-02 11:09
@danwdart I'm working on a new release schedule, there are many updates long awaited. This will be included

**Comment by danwdart** [comment] 2021-08-02 11:24
That's super good to hear. Thanks!

**Comment by jchia** [comment] 2024-01-14 11:12
0.4.18.2 was released quite a while ago, so I think the issue is fixed.

**Closed by jchia** 2024-01-14 11:12 UTC

**Comment by danwdart** [comment] 2024-01-14 17:38
So it was. Thanks
